#!/usr/bin/env node
/**
 * Copilot adapter — Installer
 *
 * Sets up .github/copilot-instructions.md and a VS Code settings task
 * to capture edits for GitHub Copilot.
 *
 * Copilot reads .github/copilot-instructions.md as extra context
 * for code generation. We inject the taste profile there.
 */

const fs = require('fs');
const path = require('path');

const TASTE_DIR = path.resolve(__dirname, '../..');

function install(projectDir) {
  projectDir = projectDir || process.cwd();
  const githubDir = path.join(projectDir, '.github');
  const instructionsFile = path.join(githubDir, 'copilot-instructions.md');
  const vscodeDir = path.join(projectDir, '.vscode');
  const tasksFile = path.join(vscodeDir, 'tasks.json');

  // Ensure .github/ exists
  if (!fs.existsSync(githubDir)) {
    fs.mkdirSync(githubDir, { recursive: true });
  }

  // Write .github/copilot-instructions.md header (content gets refreshed by injector)
  const header = `# Taste Profile

This file is auto-generated by Taste Engine (https://github.com/claude-code/taste-engine).
It captures coding style preferences learned from your edits.
Do not edit manually — your changes will be overwritten on next injection.

## Active Preferences

${getInjectionContent()}

## How to Update

Preferences are learned automatically as you edit. To refresh this file:
\`\`\`bash
node ~/.claude/skills/taste/adapters/shared/taste-platform-inject.js --target copilot-instructions
\`\`\`
`;

  fs.writeFileSync(instructionsFile, header);
  console.log('[copilot] Wrote ' + instructionsFile);

  // Set up VS Code task to capture on-save (optional)
  if (!fs.existsSync(vscodeDir)) {
    fs.mkdirSync(vscodeDir, { recursive: true });
  }

  const taskConfig = {
    version: '2.0.0',
    tasks: [
      {
        label: 'taste-capture',
        type: 'shell',
        command: 'node',
        args: [
          TASTE_DIR + '/adapters/shared/taste-platform-capture.js',
          '${file}',
        ],
        runOn: 'folderOpen',
        problemMatcher: [],
        presentation: { echo: false, reveal: 'silent', focus: false },
      },
    ],
  };

  // Only write tasks.json if it doesn't exist or doesn't have our task
  let existingTasks = {};
  if (fs.existsSync(tasksFile)) {
    try { existingTasks = JSON.parse(fs.readFileSync(tasksFile, 'utf8')); } catch (e) {}
  }

  const existingLabels = (existingTasks.tasks || []).map(t => t.label);
  if (!existingLabels.includes('taste-capture')) {
    if (!existingTasks.tasks) existingTasks.tasks = [];
    existingTasks.tasks.push(taskConfig.tasks[0]);
    fs.writeFileSync(tasksFile, JSON.stringify(existingTasks, null, 2));
    console.log('[copilot] Updated ' + tasksFile);
  }

  console.log('[copilot] ✓ Taste Engine active for GitHub Copilot');
}

function getInjectionContent() {
  try {
    const { spawnSync } = require('child_process');
    const injector = TASTE_DIR + '/adapters/shared/taste-platform-inject.js';
    const result = spawnSync('node', [injector, '--target', 'stdout'], {
      timeout: 5000,
      stdio: 'pipe',
    });
    if (result.status === 0) return result.stdout.toString().trim();
  } catch (e) {}
  return 'No preferences learned yet. Edit some code to build your taste profile.';
}

const args = process.argv.slice(2);
install(args[0] || process.cwd());
