#!/usr/bin/env node
/**
 * Aider adapter — Installer
 *
 * Sets up:
 *   1. CONVENTIONS.md — Aider reads this for project conventions
 *   2. Git post-commit hook — Captures patterns after each commit
 *   3. .aider.conf.yml — Optional aider config
 *
 * Aider reads CONVENTIONS.md as system context for code generation.
 * The git hook captures every committed diff for taste extraction.
 */

const fs = require('fs');
const path = require('path');
const { spawnSync } = require('child_process');

const TASTE_DIR = path.resolve(__dirname, '../..');
const INJECT = TASTE_DIR + '/adapters/shared/taste-platform-inject.js';
const CAPTURE = TASTE_DIR + '/adapters/shared/taste-platform-capture.js';

function install(projectDir) {
  projectDir = projectDir || process.cwd();
  const hooksDir = path.join(projectDir, '.git', 'hooks');
  const conventionsFile = path.join(projectDir, 'CONVENTIONS.md');
  const aiderConfigFile = path.join(projectDir, '.aider.conf.yml');

  // ── 1. CONVENTIONS.md ──
  const injectResult = spawnSync('node', [INJECT, '--target', 'stdout'], {
    timeout: 5000,
    stdio: 'pipe',
  });
  const tasteContent = injectResult.status === 0 ? injectResult.stdout.toString().trim() : 'No preferences learned yet.';

  let conventionsContent = '# Conventions\n\n## Coding Style\n\nAuto-generated by Taste Engine.\n\n';
  if (fs.existsSync(conventionsFile)) {
    conventionsContent = fs.readFileSync(conventionsFile, 'utf8');
    if (!conventionsContent.includes('Taste Engine')) {
      conventionsContent += '\n\n## Taste Profile (auto-generated)\n\n' + tasteContent + '\n';
    }
  } else {
    conventionsContent += tasteContent + '\n';
  }
  fs.writeFileSync(conventionsFile, conventionsContent);
  console.log('[aider] Wrote ' + conventionsFile);

  // ── 2. Git post-commit hook ──
  const hookFile = path.join(hooksDir, 'post-commit');
  const hookScript = `#!/bin/sh
# Taste Engine — post-commit hook
# Captures committed changes for taste extraction
DIFF=$(git diff HEAD~1 --name-only 2>/dev/null || echo "")
if [ -n "$DIFF" ]; then
  echo "$DIFF" | while read file; do
    if [ -f "$file" ]; then
      node "${CAPTURE}" "$file" 2>/dev/null || true
    fi
  done
fi
`;

  if (fs.existsSync(hooksDir)) {
    // Check if hook already exists
    let existingHook = '';
    if (fs.existsSync(hookFile)) {
      existingHook = fs.readFileSync(hookFile, 'utf8');
    }

    if (!existingHook.includes('Taste Engine')) {
      // If existing hook has content, prepend ours
      const finalHook = existingHook
        ? hookScript + '\n# Original hook continues below:\n' + existingHook
        : hookScript;

      fs.writeFileSync(hookFile, finalHook);
      fs.chmodSync(hookFile, '755');
      console.log('[aider] Installed git post-commit hook');
    } else {
      console.log('[aider] Git hook already installed');
    }
  } else {
    console.log('[aider] No .git/hooks/ found — skipping post-commit hook');
    console.log('[aider] Run `git init` first or install manually');
  }

  // ── 3. .aider.conf.yml ──
  let aiderConfig = '';
  if (fs.existsSync(aiderConfigFile)) {
    aiderConfig = fs.readFileSync(aiderConfigFile, 'utf8');
  }

  if (!aiderConfig.includes('CONVENTIONS.md')) {
    const additions = '\n# Taste Engine\nconventions-file: CONVENTIONS.md\n';
    fs.appendFileSync(aiderConfigFile, additions);
    console.log('[aider] Updated .aider.conf.yml');
  }

  console.log('[aider] ✓ Taste Engine active for Aider');
}

install(process.argv[2] || process.cwd());
